"""Rung B — reproduce the NICER code-comparison SD1a waveform (v0.8.1).

The Rung A test pinned our pipeline to a closed form *we* derived. Rung B is the
credibility step: reproduce a published test case from the NICER pulse-profile
**code-comparison** suite (Bogdanov et al. 2019, ApJL 887, L26), whose reference
profiles were generated by the independent Illinois–Maryland (IM) ray-tracing
code and agreed across all the community codes to ≲ 0.1%.

Test **SD1a** (their Table 1) is the one case that maps onto our machinery with
no new physics:

  - ν = 1 Hz  → surface v/c ≈ 2.5e-4, so Doppler/aberration are negligible
    (≪ their 0.1% bar): this is the pure Schwarzschild light-bending limit.
  - angular radius 0.01 rad ≈ 0.6°  → effectively a **point spot** (our model).
  - isotropic ("iso") Planck emission  → our default isotropic beaming; with no
    Doppler the *normalized* profile shape is achromatic, so our bolometric curve
    and their monochromatic-at-1-keV curve share the same shape.
  - i = θ_s = 90°, M = 1.4 M_sun, R = 12 km  → compactness u = 2GM/Rc² ≈ 0.3445.

The spot crosses fully behind the star, so this is an *eclipsing* geometry
(F_min = 0, PF = 1); the test is the **profile shape** and the bending-set
**eclipse width** (gravity lets us see ≈ 32° around the back on each side).

Our only approximation relative to the IM code is the Beloborodov (2002) linear
bending map (exact to ~1% for u ≲ 0.5), so agreement is expected at the ~1%
level — worst at the grazing eclipse edges — rather than their 0.1%.

Reference data: the L26 supplementary archive (apjlab5968.tar.gz), file
``SD1a_test_IM.txt`` — two columns: rotational phase (cycles) and photon flux
(photons/cm²/s/keV). Extracted to ``data/l26_reference/``.

Run from the repository root:  python scripts/rung_b_compare.py
"""

import numpy as np
import matplotlib.pyplot as plt

from mcrt import point_spot_flux

# SD1a parameters (Bogdanov et al. 2019, ApJL 887 L26, Table 1).
M_SUN_KM = 1.47662          # GM_sun/c² in km
NS_MASS_MSUN = 1.4
NS_RADIUS_KM = 12.0
INCLINATION_DEG = 90.0      # colatitude of observer
COLATITUDE_DEG = 90.0       # colatitude of spot center
COMPACTNESS = 2.0 * M_SUN_KM * NS_MASS_MSUN / NS_RADIUS_KM   # u = 2GM/Rc² ≈ 0.3445

REFERENCE_PATH = "data/l26_reference/SD1a_test_IM.txt"
FIGURE_PATH = "data/pulse_profile_rung_b.png"


def load_reference(path: str = REFERENCE_PATH):
    """Return (phase_cycles, photon_flux) for the IM SD1a reference waveform."""
    ref = np.loadtxt(path)
    return ref[:, 0], ref[:, 1]


def our_profile_at(phase_cycles: np.ndarray) -> np.ndarray:
    """Our point-spot flux at the reference phases (both peak at phase 0)."""
    i, theta = np.deg2rad(INCLINATION_DEG), np.deg2rad(COLATITUDE_DEG)
    phi = 2.0 * np.pi * phase_cycles                      # cycles → radians
    return point_spot_flux(phi, i, theta, COMPACTNESS)


def main():
    phase, f_ref = load_reference()
    f_ours = our_profile_at(phase)

    # Normalize each curve to its own peak: ours is in arbitrary units, theirs is
    # an absolute photon flux. At 1 Hz + isotropic the normalized shapes coincide,
    # which is exactly the identity Rung B tests.
    ref_n = f_ref / f_ref.max()
    ours_n = f_ours / f_ours.max()
    resid = ours_n - ref_n
    max_abs = float(np.abs(resid).max())
    rms = float(np.sqrt((resid ** 2).mean()))

    fig, (ax, ax_r) = plt.subplots(
        2, 1, figsize=(8, 6.6), height_ratios=[3, 1], sharex=True, layout="constrained"
    )

    ax.plot(phase, ref_n, "-", lw=2, color="#1f77b4",
            label="IM code reference (Bogdanov+ 2019, SD1a)")
    ax.plot(phase[::3], ours_n[::3], "o", ms=4.5, color="#d62728",
            label="this work (Beloborodov bending)")
    ax.set_ylabel("normalized flux  F(φ) / F_max")
    ax.set_title(f"Rung B: SD1a waveform vs. NICER code-comparison reference  "
                 f"(u={COMPACTNESS:.3f}, i=θ_s=90°)")
    ax.legend(loc="upper center", fontsize=9)
    ax.margins(x=0.01)

    ax_r.axhline(0.0, color="#bbbbbb", lw=0.8)
    ax_r.plot(phase, 100.0 * resid, "-", color="#555555", lw=1)
    ax_r.set_xlabel("rotational phase  φ / 2π  [cycles]")
    ax_r.set_ylabel("Δ  [% of peak]")
    ax_r.set_title(f"this work − reference   (max |Δ| = {100*max_abs:.2f}%, "
                   f"RMS = {100*rms:.2f}% — worst at the grazing eclipse edge)")

    fig.savefig(FIGURE_PATH, dpi=130)
    print(f"saved {FIGURE_PATH}")

    vis_ref = (ref_n > 0).mean()
    vis_ours = (ours_n > 0).mean()
    print(f"  u = {COMPACTNESS:.5f}")
    print(f"  visible fraction:  reference {vis_ref:.4f}   ours {vis_ours:.4f}")
    print(f"  max|Δ| = {100*max_abs:.3f}%   RMS Δ = {100*rms:.3f}%")
    print(f"  worst point at phase {phase[np.abs(resid).argmax()]:.3f} (eclipse edge)")


if __name__ == "__main__":
    main()
